import React from 'react';
import SectionTitle from '../Home/SectionTitle';

export default function Privacy(){
    return(
        <React.Fragment>
           <div style={{paddingTop: 80}}>
              <SectionTitle title="PRIVACY"/>  
           </div> 
           <section id="about" class="about" style={{backgroundColor: '#fff'}}>
               <div class="container">  
                   <div class="row">
                   <div class="col-lg-12 col-md-12 d-flex align-items-stretch">
                        <p class="animated fadeInDown" style={{textAlign: 'justify'}}>
                              This privacy policy applies to the information Sterde Limited (Sterde) and its related companies and/or websites collect about you from any device you use to access Sterde products, services, software, websites, and other goods and services offered, owned, or operated by Sterde. (together "Services"). Some of these Services may provide you with additional information and choices about your privacy, which you should review. This Policy does not apply to information about you collected by third party websites and offerings linked to or otherwise accessible from Sterde. The data collected or received by third parties is subject to their privacy policies.<br /><br />
                              <strong>Collection of Your Information</strong><br />
                              We collect or receive information about your interactions with Sterde and its related websites. Registering with Sterde is optional, and we may collect information even if you do not register. Depending on how you use Sterde's Services, your Sterde information may include registration-related information (such as name, addresses, email addresses, telephone numbers, birth date, or gender); information about the Sterde Services that you use, how frequently you use them (such as your use of email); and your responses to the offerings and advertisements presented on Sterde or other features made available by Sterde, including those available on third party websites; information about the searches you perform through Sterde Services and how you use the results of those searches; personal financial information related to the use of Sterde financial features. Your use of Sterde financial features may be subject to additional terms (see personal financial information below). Transaction-related information (such as credit card or other preferred means of payment, billing or shipping information, or a history of products purchased through Sterde);  customer service information about you as a Sterde user;  Location data and other information about devices used to access and interact with Sterde; other information specifically related to your use of Services, including information that you publicly post using tools made available by Sterde.<br />
                              Your Sterde information may be supplemented with additional information from other companies such as publicly available information, information about households, and other information which we may append or match to your Sterde information. Sterde may also receive or collect certain technical information when you use our Services. This may include your browser or operating system, your manner of connecting to the Internet (including the type of device you are using) and the name of your Internet service provider or wireless carrier; your Internet protocol (IP) address; information about Sterde Services that you used before registering with Sterde; and data relating to malfunctions or problems occurring when you use Sterde Services. Additionally, we may collect information about other software on your device for the limited purpose of protecting your security or improving your online experience.<br /><br />
                              <strong>How Your Sterde Information is used</strong><br />
                              Your Sterde information is used for purposes that include: to operate and improve the Services available through Sterde; to personalize the content and advertisements provided to you (including to present offers to you on behalf of business partners and advertisers); to fulfill your requests for products, programs, and services; to communicate with you and respond to your inquiries; to conduct research about your use of Sterde; to help offer you other products, programs, or services that may be of interest. Sterde may use cookies, web beacons or other technologies in combination with your Sterde information to enhance and personalize your experience with Sterde.  Sterde may use information about your use of certain communication tools (for example, Pawapins); however, when you use Sterde communication tools, Sterde does not read your private online communications without your consent.<br /><br />
                              <strong>Sharing of Your Sterde Information</strong><br />
                              Sterde does not rent or sell your Sterde information (such as name, address, telephone number, screen name, and credit card information) to third parties for their marketing purposes. Sterde may share your Sterde information with third parties to provide products and services you have requested when we have your consent or as described in this Privacy Policy. Your Sterde information may be shared with sites and services consistent with this Privacy Policy. The contents of your online communications, as well as other information about you as a Sterde user, may be accessed and disclosed under the following circumstances: in response to lawful governmental requests or legal process (for example, a court order, search warrant or subpoena), in other circumstances in which Sterde has a good faith belief that a crime has been or is being committed by a Sterde user, that an emergency exists that poses a threat to the safety of you or another person, when necessary either to protect the rights or property of Sterde or for us to render the service you have requested. Please note that if you use Sterde communications tools to disclose information about yourself publicly (for example, in chat rooms or online message platforms), others outside of Sterde may obtain access to the information you provide. Sterde's offerings may include features or functionalities provided by third parties. In the process of providing such functionalities within Sterde Services, your browser may automatically send certain technical information to the third-party provider. The use of these third-party provided features or functionalities is subject to their own privacy policies. Business partners or other third parties may receive data about groups of Sterde users, but do not receive information that personally identifies you. We may use agents and contractors in order to help operate Sterde. Their use of information is limited to these purposes. In the event that ownership of Sterde was to change as a result of a merger, acquisition, or transfer to another company, your Sterde information may be transferred.<br /><br />
                              <strong>Display of Advertising</strong><br />
                             
                              Your Sterde information may be used for the presentation of advertisements. Sterde may use ad networks to customize and display advertising on Sterde Services. Sterde may share certain information about you as a user (such as age, zip code, or other information we have collected or received) with certain ad network and service providers to help them deliver more relevant content and advertisements through their networks.<br /><br/>
                             <strong>Our Commitment to Security</strong><br />
                             Sterde has established safeguards to help prevent unauthorized access to or misuse of your Sterde information, but cannot guarantee that your information will never be disclosed in a manner inconsistent with this Privacy Policy (for example, as a result of unauthorized acts by third parties that violate applicable law or Sterde and its affiliated providers' policies). To protect your privacy and security, we may use passwords or other technologies to register or authenticate you and enable you to take advantage of Sterde Services, and before granting access or making corrections to your Sterde information. <br /><br />
                            <strong>Children's Privacy</strong><br />
                            Sterde Services are intended for a general audience.  We do not knowingly collect, use, or disclose personal information from children who are minors. By providing your personal information for general Services, you agree that Sterde will not be liable in any way if you are a minor. Users of Sterde Services using Services not intended for minors; however, they agree that they are not minors.<br /><br />
                            <strong>Changes to this Privacy Policy and Additional Information</strong><br />
                            Sterde may update this Privacy Policy from time to time. You may be provided other privacy-related information in connection with your use of offerings from Sterde as well as for special features and services not described in this Policy that may be introduced in the future.<br/><br/>
                            <strong>Personal Financial Information</strong><br />
                            Sterde may collect personal financial information when you use Sterde financial features (such as Pawapins). Sterde does not disclose information from the use of Sterde financial features to unaffiliated third parties other than in the limited circumstances permitted by law (for example, in response to legal process). This Policy does not apply, however, to the financial information that you provide to a third party in connection with your use of their sites or offerings. Only employees and contractors who need to know this information in order to provide this service to you are authorized to access Sterde financial information.
                             
                        </p>
                    </div>
                   </div>
                </div>
           </section>
        </React.Fragment>
    )
}